"""Strategy implementations. Import here to trigger registration."""
from . import ma60_breakthrough                  # noqa: F401
from . import ma60_breakthrough_basic_time_stop  # noqa: F401
from . import ma60_breakthrough_full             # noqa: F401
from . import ma120_breakthrough                  # noqa: F401
from . import ma120_breakthrough_basic_time_stop  # noqa: F401
from . import ma120_breakthrough_full             # noqa: F401
from . import ma55_breakthrough                  # noqa: F401
from . import ma55_breakthrough_basic_time_stop  # noqa: F401
from . import ma55_breakthrough_full             # noqa: F401
from . import ma144_breakthrough                  # noqa: F401
from . import ma144_breakthrough_basic_time_stop  # noqa: F401
from . import ma144_breakthrough_full             # noqa: F401
from . import ma_pullback_breakthrough           # noqa: F401
from . import ma_pullback_breakthrough_basic_time_stop  # noqa: F401
from . import ma_pullback_breakthrough_full      # noqa: F401
from . import ma_special_pullback_breakthrough           # noqa: F401
from . import ma_special_pullback_breakthrough_basic_time_stop  # noqa: F401
from . import ma_special_pullback_breakthrough_full  # noqa: F401
